#!/bin/bash

gcc matrixmult_thread.c -o matrixmult_thread -std=c99 -lpthread -w
chmod 755  matrixmult_thread
for i in {1..5}
do
	echo "Size: 128x128 Threads: 1"
	time -p ./matrixmult_thread input/matrix1_128.txt input/matrix2_128.txt result.txt 1
	echo ""
	echo "Size: 128x128 Threads: 4"
	time -p ./ matrixmult_thread input/matrix1_128.txt input/matrix2_128.txt result.txt 4
	echo ""
	echo "Size: 128x128 Threads: 16"
	time -p ./ matrixmult_thread input/matrix1_128.txt input/matrix2_128.txt result.txt 16
	echo ""
	echo "Size: 128x128 Threads: 64"
	time -p ./ matrixmult_thread input/matrix1_128.txt input/matrix2_128.txt result.txt 64
	echo ""
	echo "Size: 128x128 Threads: 256"
	time -p ./ matrixmult_thread input/matrix1_128.txt input/matrix2_128.txt result.txt 256
	echo " "
done
echo " "
for i in {1..5}
do
	echo "Size: 256x256 Threads: 1"
	time -p ./ matrixmult_thread input/matrix1_256.txt input/matrix2_256.txt result.txt 1
	echo " "
	echo "Size: 256x256 Threads: 4"
	time -p ./ matrixmult_thread input/matrix1_256.txt input/matrix2_256.txt result.txt 4
	echo " "
	echo "Size: 256x256 Threads: 16"
	time -p ./ matrixmult_thread input/matrix1_256.txt input/matrix2_256.txt result.txt 16
	echo " "
	echo "Size: 256x256 Threads: 64"
	time -p ./ matrixmult_thread input/matrix1_256.txt input/matrix2_256.txt result.txt 64
	echo " "
	echo "Size: 256x256 Threads: 256"
	time -p ./ matrixmult_thread input/matrix1_256.txt input/matrix2_256.txt result.txt 256
	echo " "
done
echo " "

for i in {1..5}
do
	echo "Size: 512x512 Threads: 1"
	time -p ./ matrixmult_thread input/matrix1_512.txt input/matrix2_512.txt result.txt 1
	echo " "
	echo "Size: 512x512 Threads: 4"
	time -p ./ matrixmult_thread input/matrix1_512.txt input/matrix2_512.txt result.txt 4
	echo " "
	echo "Size: 512x512 Threads: 16"
	time -p ./ matrixmult_thread input/matrix1_512.txt input/matrix2_512.txt result.txt 16
	echo " "

	echo "Size: 512x512 Threads: 64"
	time -p ./ matrixmult_thread input/matrix1_512.txt input/matrix2_512.txt result.txt 64
	echo " "
	echo "Size: 512x512 Threads: 256"
	time -p ./ matrixmult_thread input/matrix1_512.txt input/matrix2_512.txt result.txt 256
	echo " "
done
# echo " "
for i in {1..5}
do
	echo "Size: 1024x1024 Threads: 1"
	time -p ./ matrixmult_thread input/matrix1_1024.txt input/matrix2_1024.txt result.txt 1
	echo " "
	echo "Size: 1024x1024 Threads: 4"
	time -p ./ matrixmult_thread input/matrix1_1024.txt input/matrix2_1024.txt result.txt 4
	echo " "
	echo "Size: 1024x1024 Threads: 16"
	time -p ./ matrixmult_thread input/matrix1_1024.txt input/matrix2_1024.txt result.txt 16
	echo " "
	echo "Size: 1024x1024 Threads: 64"
	time -p ./ matrixmult_thread input/matrix1_1024.txt input/matrix2_1024.txt result.txt 64
	echo " "
	echo "Size: 1024x1024 Threads: 256"
	time -p ./ matrixmult_thread input/matrix1_1024.txt input/matrix2_1024.txt result.txt 256
done

for i in {1..5}
do
echo " "
	echo "Size: 2048x2048 Threads: 1"
	time -p ./ matrixmult_thread input/matrix1_2048.txt input/matrix2_2048.txt result.txt 1
	echo " "
	echo "Size: 2048x2048 Threads: 4"
	time -p ./ matrixmult_thread input/matrix1_2048.txt input/matrix2_2048.txt result.txt 4
	echo " "
	echo "Size: 2048x2048 Threads: 16"
	time -p ./ matrixmult_thread input/mmatrix1_2048.txt input/matrix2_2048.txt result.txt 16
	echo " "
	echo "Size: 2048x2048 Threads: 64"
	time -p ./ matrixmult_thread input/matrix1_2048.txt input/matrix2_2048.txt result.txt 64
	echo " "
	echo "Size: 2048x2048 Threads: 256"
	time -p ./ matrixmult_thread input/matrix1_2048.txt input/matrix2_2048.txt result.txt 256
done